user:
  name: Lance Wu
  avatar: /images/avatar.jpg
  location: Christchurch, New Zealand
  description:
  footnotes:

# config you SNS
social:
  zhihu:
  twitter:
  facebook:
  linkedin:
  instagram:
  github: Nulllance

# Page icon
favicon: images/blog.ico

friend_links:
  - title: Link1
    link: https://www.link1.test.com/
  # main menu navigation
menu:
  Home: /
  About: /about
  Archives: /archives

widgets:
  - tag
  - archive
  - category
  - recent_posts
comment_valine:
  enable: true
  appId:
  appKey:
highlight:
  enable: true
